### ISSUE TITLE
insanely outdated speex version, add new to overlay?

### ISSUE THREAD

**Issue by YogSottot** [YogSottot/ring-overlay#3]
Speex 1.2rc1 is out July 23, 2008 - in portage now, https://bugs.gentoo.org/show_bug.cgi?id=596400
Speex 1.2.0 out December 7, 2016
#1 
Also speexdsp now included in media-libs/speex-1.2_rc1 but starting from 1.2_rc2 it is separated to Speex and SpeexDSP. And speexdsp package not in any overlay.

**Comment by stefan-langenmaier** [comment]
I think speexdsp is only used on Android so it could be ignored.

We could add the newer version until it's in the main repository.
