### ISSUE TITLE
expand keywords?

### ISSUE THREAD

**Issue by YogSottot** [YogSottot/ring-overlay#4]
#1 
```
case "$HOST" in
	amd64-*)
		ARCH="x86_64"
		;;
	i[3456]86-*)
		ARCH="i386"
		;;
	powerpc-*|ppc-*)
		ARCH="ppc"
		;;
	powerpc64-*|ppc64-*)
		ARCH="ppc64"
```

**Comment by YogSottot** [comment]
Should be add at least i386?

**Comment by stefan-langenmaier** [comment]
I think this should be an easy next step. I had it limited to amd64 because of the gmp dependency. When the bundled code was used some environment variable trickery had to be done.

This problem should now be "solved".
