### ISSUE TITLE
opendht has bundled argon2 src

### ISSUE THREAD

**Issue by YogSottot** [YogSottot/ring-overlay#6]
#1 
opendht has bundled argon2 src, it can be unbundled with a small patch.
https://github.com/savoirfairelinux/opendht/issues/83
	app-crypt/argon2

**Comment by stefan-langenmaier** [comment]
I have nothing against it. :)

**Comment by stefan-langenmaier** [comment]
I think you can reopen this issue.

**Comment by YogSottot** [comment]
fixed

**Comment by aberaud** [comment]
[OpenDHT 1.3.1]( https://github.com/savoirfairelinux/opendht/releases/tag/1.3.1 ) adds native support for system argon2 (enabled by default).

**Comment by stefan-langenmaier** [comment]
I have seen the change (because the patch in the ebuild failed), unfortunately it doesn't pick up the installed argon2 library for me. I haven't had the time yet to inspect why.

**Comment by aberaud** [comment]
might be because argon2 install target doesn't install a pkgconfig file (but provides an example one)
